[server]
headless = true

[theme]
primaryColor = "#1E90FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"

[app]
# aqui você define o arquivo principal do app
mainPage = "login.py"
