GOOGLE_API_KEY = "AIzaSyAm8CzTMs0Qk8yo0UWMLETaBMCDFsE3Ixk"
SQLSERVER_HOST = "kpm.sql.headcargo.com.br,9322"
SQLSERVER_DATABASE = "HeadCARGO_KPM"
SQLSERVER_USER = "hc_kpm_ti"
SQLSERVER_PASSWORD = "971639DA-D739-4C0F-83D5-6E34037092FD"
POSTGRES_USER = "kpm"
POSTGRES_PASSWORD = "@Kpm<102030>"
POSTGRES_HOST = "89.117.17.6"
POSTGRES_PORT = "5432"
POSTGRES_DATABASE = "pdf_data"
TOKEN = "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjU4YjVmNWU3LTgyYTItNDEyMS05ODM2LWY3YzliZmQ3NjM4YSIsImNvbnRhaW5lciI6ImtwbSIsImlzcyI6IkhlYWRTb2Z0IiwiYXVkIjoiRmlsZVN0cmVhbSJ9.BldzJwg8hP9eT7IiZoAE6eB7UbKoyVge9mx1fawHnVU"

[general]
TOKEN = "your_token_here"

[postgres]
DB_NAME = "pdf_data"
DB_USER = "kpm"
DB_PASSWORD = "@Kpm<102030>"
DB_HOST = "89.117.17.6"
DB_PORT = "5432"